# Generated by Django 3.0.4 on 2020-04-17 14:34

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('Application_number', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('prefer not to say', 'prefer not to say')], max_length=30, null=True, verbose_name='Gender')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('nick_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nickname')),
                ('last_name', models.CharField(max_length=255, null=True, verbose_name=' last_name')),
                ('birth_date', models.DateField(verbose_name='birth_date ')),
                ('birth_place', models.CharField(max_length=255, verbose_name='birth_place')),
                ('country', django_countries.fields.CountryField(max_length=255, verbose_name='Country')),
                ('city', models.CharField(max_length=255, null=True, verbose_name='city')),
                ('mail', models.EmailField(max_length=255, verbose_name='Mail')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone ')),
                ('educatton_level', models.CharField(blank=True, max_length=255, null=True, verbose_name='Education_Level ')),
                ('job', models.CharField(blank=True, max_length=255, null=True, verbose_name='Job ')),
                ('start_date', models.DateField(default='', null=True, verbose_name='date of start job  ')),
                ('adress1', models.CharField(blank=True, max_length=255, null=True, verbose_name='recnetly adress')),
                ('country_rec', django_countries.fields.CountryField(default='some_value', max_length=255, verbose_name='Country_rec')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
            ],
        ),
    ]
