# Generated by Django 3.0.4 on 2020-04-17 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='start_date',
        ),
    ]
