# Generated by Django 3.0.4 on 2020-06-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0004_auto_20200611_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='state_step',
            field=models.CharField(blank=True, choices=[('0', 'لم يتم البدء بالمعالجة'), ('1', 'الخطوة الاولى'), ('2', 'الخطوة الثانية'), ('3', 'الخطوة الثالثة'), ('4', 'تمت المعالجة'), ('5', 'تحميل ملفات مرفقة')], default=1, max_length=30, null=True, verbose_name='المعالجة'),
        ),
    ]
