# Generated by Django 3.0.4 on 2020-06-11 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0006_auto_20200611_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='support_org_state_1',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='formula.Support_descrption', verbose_name='الجهة المحولة'),
        ),
    ]
