# Generated by Django 3.0.4 on 2020-06-11 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0010_auto_20200611_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='org_memeber',
            field=models.CharField(blank=True, choices=[('0', 'نعم'), ('1', 'لا')], max_length=255, null=True, verbose_name='هل كنت عضوا في أحد المجمعات الصحفية'),
        ),
    ]
