# Generated by Django 3.0.4 on 2020-06-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0013_auto_20200611_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='other_org_demand',
            field=models.CharField(blank=True, choices=[('0', 'نعم'), ('1', 'لا')], max_length=255, null=True, verbose_name='هل تقدمت بطلب مساعدة لأي منظمة سابقاً؟ '),
        ),
    ]
