# Generated by Django 3.0.4 on 2020-06-11 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0014_auto_20200611_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='city',
            field=models.CharField(choices=[('aleppo', 'Aleppo'), ('damascus', 'Damascus'), ('daraa', 'Daraa'), ('deir ez-Zor', 'Deir ez-Zor'), ('hama', 'Hama'), ('al-Hasakah', 'Al-Hasakah'), ('homs', 'Homs'), ('idlib', 'Idlib'), ('latakia', 'Latakia'), ('quneitra', 'Quneitra'), ('raqqa', 'Raqqa'), ('as-Suwayda', 'As-Suwayda'), ('tartus', 'Tartus'), ('other', 'other')], max_length=255, null=True, verbose_name='المدينة'),
        ),
    ]
