# Generated by Django 3.0.4 on 2020-06-11 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0015_auto_20200612_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportorg',
            name='date_of_response',
            field=models.DateField(blank=True, verbose_name='تاريخ الإحالة '),
        ),
        migrations.AlterField(
            model_name='supportorg',
            name='date_of_result',
            field=models.DateField(blank=True, verbose_name='تاريخ الإحالة '),
        ),
    ]
