# Generated by Django 3.0.4 on 2020-06-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0016_auto_20200612_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='medical_state_inf',
            field=models.CharField(blank=True, choices=[('0', 'نعم'), ('1', 'لا')], default=1, max_length=255, null=True, verbose_name='هل لديك وضع صحي خاص '),
        ),
    ]
