# Generated by Django 3.0.4 on 2020-06-12 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0017_auto_20200612_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='have_kids',
            field=models.CharField(blank=True, choices=[('0', 'نعم'), ('1', 'لا')], default=1, max_length=255, null=True, verbose_name='هل لديك أولاد؟'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='org_memeber',
            field=models.CharField(blank=True, choices=[('0', 'نعم'), ('1', 'لا')], default=1, max_length=255, null=True, verbose_name='هل كنت عضوا في أحد المجمعات الصحفية'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='paid_job',
            field=models.CharField(blank=True, choices=[('0', 'نعم'), ('1', 'لا')], default=1, max_length=255, null=True, verbose_name='هل عملت بإجر مسبقاُ'),
        ),
    ]
