# Generated by Django 3.0.4 on 2020-07-20 15:12

from django.db import migrations, models
import formula.validators


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0019_auto_20200720_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='document_1',
            field=models.FileField(blank=True, default='', null=True, upload_to='documents/', validators=[formula.validators.validate_file_extensison], verbose_name='ملف 1'),
        ),
        migrations.AddField(
            model_name='registration',
            name='document_2',
            field=models.FileField(blank=True, default='', null=True, upload_to='documents/', validators=[formula.validators.validate_file_extensison], verbose_name='ملف 2'),
        ),
    ]
