# Generated by Django 3.0.4 on 2020-07-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0020_auto_20200720_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='date_of_violations',
            new_name='date_of_violations_1',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='kind_of_violation',
        ),
        migrations.AddField(
            model_name='registration',
            name='kind_of_violation_1',
            field=models.CharField(blank=True, choices=[('0', ' اعتقال'), ('1', 'اختطاف'), ('2', 'منع من العمل'), ('3', 'مصادرة معدات'), ('4', 'اعتداء بالضرب'), ('5', 'اصابة'), ('6', 'تهديد'), ('7', 'ابتزاز'), ('8', 'غير ذلك')], max_length=255, null=True, verbose_name=' لأي نوع من أنواع الانتهاكات؟ '),
        ),
    ]
