# Generated by Django 3.0.4 on 2020-07-24 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0022_auto_20200723_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_violation', models.DateField(blank=True, verbose_name='تاريخ الانتهاك ')),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula.Registration')),
            ],
        ),
    ]
