# Generated by Django 3.0.4 on 2020-07-24 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0023_violation'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='violation_type',
            field=models.CharField(max_length=200, null=True, verbose_name='نوع الانتهاك'),
        ),
    ]
