# Generated by Django 3.0.4 on 2020-07-29 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0026_auto_20200729_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='nick_name',
        ),
    ]
