# Generated by Django 3.0.4 on 2020-07-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0029_registration_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='حساب الفيسبوك'),
        ),
    ]
