# Generated by Django 3.0.4 on 2020-07-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0030_registration_facebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='educatton_level',
            field=models.CharField(blank=True, choices=[('0', 'مادون الثانوي '), ('1', 'الثانوي'), ('2', 'الجامعي'), ('3', 'ما بعد جامعي')], max_length=255, null=True, verbose_name=' التحصيل العلمي   '),
        ),
    ]
