# Generated by Django 3.0.4 on 2020-07-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0032_auto_20200729_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='family_state',
            field=models.CharField(choices=[('متزوج', 'متزوج'), ('عازب', 'عازب')], default='عازب', max_length=30, null=True, verbose_name='الوضع العائلي'),
        ),
    ]
