# Generated by Django 3.0.4 on 2020-07-29 14:37

from django.db import migrations, models
import formula.validators


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0034_auto_20200729_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='document_1',
            field=models.FileField(blank=True, null=True, upload_to='documents/', validators=[formula.validators.validate_file_extensison], verbose_name='ملف 1'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='family_state',
            field=models.CharField(choices=[('متزوج', 'متزوج/ة'), ('عازب', 'عازب/ة')], default='عازب', max_length=30, null=True, verbose_name='الوضع العائلي'),
        ),
    ]
