# Generated by Django 3.0.4 on 2020-07-29 14:59

from django.db import migrations, models
import formula.validators


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0035_auto_20200729_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='document_1',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', validators=[formula.validators.validate_file_extensison], verbose_name='ملف 1'),
        ),
    ]
