# Generated by Django 3.0.4 on 2020-07-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0036_auto_20200729_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='document_1',
            field=models.ImageField(upload_to='documents/'),
        ),
    ]
