# Generated by Django 3.0.4 on 2020-07-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0039_auto_20200730_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='document_1',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='document_2',
        ),
        migrations.AddField(
            model_name='registration',
            name='image',
            field=models.FileField(default='', upload_to='images/'),
        ),
    ]
