# Generated by Django 3.0.4 on 2020-07-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0040_auto_20200730_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='image',
        ),
        migrations.AddField(
            model_name='registration',
            name='document_1',
            field=models.ImageField(blank=True, null=True, upload_to='documents/', verbose_name='ملف 1'),
        ),
    ]
