# Generated by Django 3.0.4 on 2020-07-30 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0041_auto_20200730_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='docs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='documents/')),
                ('docs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula.Registration', verbose_name='docs')),
            ],
        ),
    ]
