# Generated by Django 3.0.4 on 2020-07-30 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0042_docs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='docs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formula.Registration', verbose_name='tt'),
        ),
    ]
