# Generated by Django 3.0.4 on 2020-08-03 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0046_auto_20200730_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docs',
            options={'verbose_name': ' ملفات'},
        ),
    ]
