# Generated by Django 3.0.4 on 2020-08-03 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0047_auto_20200803_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='articls_link_2',
        ),
        migrations.AlterField(
            model_name='registration',
            name='articls_link_1',
            field=models.URLField(blank=True, null=True, verbose_name='روابط إعلامية منشورة باسمك الصريح أو المستعار'),
        ),
    ]
