# Generated by Django 3.0.4 on 2020-08-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0048_auto_20200803_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='articls_link_1',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='روابط إعلامية منشورة باسمك الصريح أو المستعار'),
        ),
    ]
