# Generated by Django 3.0.4 on 2020-08-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0050_auto_20200804_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='training_media',
            field=models.CharField(blank=True, choices=[('0', 'نعم'), ('1', 'لا')], default=1, max_length=255, null=True, verbose_name='هل سبق أن شاركت بأي ورشات أو دورات لتطوير الخبرات الإعلامية أو الحقوقية؟'),
        ),
    ]
