# Generated by Django 3.0.4 on 2020-08-04 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0052_auto_20200804_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='document_1',
        ),
        migrations.AlterField(
            model_name='registration',
            name='Previous_employers',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='جهة العمل السابقة'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='current_org_comp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='جهة العمل الحالية'),
        ),
    ]
