# Generated by Django 2.2.12 on 2020-08-11 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0053_auto_20200804_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='Previous_employers',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='current_org_comp',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='name_of_company_paid',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='paid_job',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='start_date',
        ),
        migrations.AddField(
            model_name='registration',
            name='date_stop_work',
            field=models.DateField(default=None, null=True, verbose_name='منذ متى منقطع/ة  عن العمل الاعلامي'),
        ),
        migrations.AddField(
            model_name='registration',
            name='facebook_state_inf',
            field=models.CharField(blank=True, choices=[('0', 'لا'), ('1', 'نعم')], default=0, max_length=255, null=True, verbose_name='هل لديك حساب فيسبوك ؟ '),
        ),
        migrations.AddField(
            model_name='registration',
            name='if_article_linke',
            field=models.CharField(blank=True, choices=[('0', 'لا'), ('1', 'نعم')], max_length=100, null=True, verbose_name='هل لديك منشورة باسمك الصريح أو المستعار ؟'),
        ),
        migrations.AddField(
            model_name='registration',
            name='if_stop_work',
            field=models.CharField(blank=True, choices=[('0', 'لا'), ('1', 'نعم')], max_length=100, null=True, verbose_name='هل انت منقطع/ة  عن العمل الاعلامي ؟'),
        ),
        migrations.AddField(
            model_name='registration',
            name='phone_state_inf',
            field=models.CharField(blank=True, choices=[('0', 'لا'), ('1', 'نعم')], default=0, max_length=255, null=True, verbose_name='هل لديك رقم هاتف ؟ '),
        ),
        migrations.AlterField(
            model_name='registration',
            name='articls_link_1',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='يرجى وضع الروابط اﻹعلامية المنشورة'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='details',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='يرجى ذكر التفاصيل '),
        ),
        migrations.AlterField(
            model_name='registration',
            name='educatton_level',
            field=models.CharField(blank=True, choices=[('0', 'مادون الثانوي '), ('1', 'الثانوي'), ('2', 'الجامعي'), ('3', 'ما بعد جامعي')], max_length=255, null=True, verbose_name='التحصيل العلمي'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='family_state',
            field=models.CharField(choices=[('متزوج', 'متزوج/ة'), ('أرمل', 'أرمل/ة'), ('مطلق', 'مطلق/ة'), ('عازب', 'عازب/ة')], default='عازب', max_length=30, null=True, verbose_name='الوضع العائلي'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='have_kids',
            field=models.CharField(blank=True, choices=[('0', 'لا'), ('1', 'نعم')], default=0, max_length=255, null=True, verbose_name='هل لديك أولاد؟'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='org_memeber',
            field=models.CharField(blank=True, choices=[('0', 'نعم'), ('1', 'لا')], default=1, max_length=255, null=True, verbose_name='هل أنت عضو في أي تجمع إعلامي، أو من الموقعين على مواثيق شرف إعلامية أو سواه من المبادرات المشتركة'),
        ),
        migrations.CreateModel(
            name='WorkDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=255, verbose_name='اسم الجهة المشغلة')),
                ('job_title', models.CharField(max_length=255, verbose_name='المسمى الوظيفي')),
                ('job_location', models.CharField(max_length=255, verbose_name='مكان العمل')),
                ('start_date', models.DateField(verbose_name='تاريخ بدء العمل')),
                ('until_now', models.CharField(choices=[('0', 'لا'), ('1', 'نعم')], max_length=100, verbose_name='هل تعمل حتى اﻵن ؟')),
                ('end_date', models.DateField(null=True, verbose_name='تاريخ انتهاء العمل')),
                ('if_salary', models.CharField(choices=[('0', 'لا'), ('1', 'نعم')], max_length=100, verbose_name='هل كنت تعمل بأجر ؟')),
                ('salary', models.CharField(max_length=255, null=True, verbose_name='اذكر آخر راتب تقاضيته من هذا العمل')),
                ('registration', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='registration', to='formula.Registration')),
            ],
        ),
    ]
