# Generated by Django 2.2.12 on 2020-08-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0054_auto_20200811_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='date_stop_work',
            field=models.DateField(blank=True, null=True, verbose_name='منذ متى منقطع/ة  عن العمل الاعلامي'),
        ),
    ]
