# Generated by Django 2.2.12 on 2020-08-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0055_auto_20200811_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='violation',
            name='responsibility',
            field=models.CharField(choices=[('0', 'القوات الحكومية'), ('1', 'فصائل المعارضة المسلحة'), ('2', 'الادارة الذاتية'), ('3', 'داعش'), ('4', 'غير ذلك')], max_length=100, null=True, verbose_name='من هي الجهة المسؤولة عن الانتهاك؟'),
        ),
    ]
