# Generated by Django 2.2.12 on 2020-08-11 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formula', '0059_registration_know_support_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='summary_of_help',
            field=models.TextField(blank=True, max_length=2000, verbose_name='يرى شرح الوضع الحالي'),
        ),
    ]
